backend:
  name: git-gateway
  branch: main
  # Netlify site pro autentizaci
  identity_url: "https://preeminent-kheer-b871e1.netlify.app/.netlify/identity"
  gateway_url: "https://preeminent-kheer-b871e1.netlify.app/.netlify/git"

site_url: https://jendovadilna.cz
display_url: https://jendovadilna.cz

media_folder: "assets/img/uploads"
public_folder: "/assets/img/uploads"

# Kolekce obsahu - Stránky, které budete chtít editovat
collections:
  - name: "pages" # Interní název pro CMS
    label: "Hlavní Stránky" # Zobrazovaný název v administračním rozhraní
    files:
      - name: "index"
        file: "index.md"
        label: "Úvodní Stránka"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
          - {label: "Nadpis stránky (Title)", name: "title", widget: "string"}
          - {label: "Podnadpis (Subtitle)", name: "subtitle", widget: "string"}
          - {label: "Tělo obsahu (Markdown)", name: "body", widget: "markdown"}
      - name: "kontakty"
        file: "kontakty.md"
        label: "Stránka Kontakty"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
          - {label: "Nadpis", name: "title", widget: "string"}
          - {label: "Podnadpis", name: "subtitle", widget: "string"}
          - {label: "Tělo obsahu", name: "body", widget: "markdown"}
      - name: "rozvrh"
        file: "rozvrh.md"
        label: "Stránka Rozvrh akcí"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
          - {label: "Nadpis", name: "title", widget: "string"}
          - {label: "Podnadpis", name: "subtitle", widget: "string"}
          - {label: "Tělo obsahu", name: "body", widget: "markdown"}