backend:
  # Používáme Netlify Identity pro snadné přihlášení
  name: git-gateway
  branch: main # Název vaší hlavní větve na GitHubu

publish_mode: editorial_workflow # Umožňuje recenzi obsahu před publikováním

media_folder: "assets/img/uploads" # Kam se budou nahrávat obrázky (např. assets/img/uploads)
public_folder: "/assets/img/uploads" # Cesta k obrázkům ve webu

# Kolekce obsahu - Stránky, které budete chtít editovat
collections:
  - name: "pages" # Interní název pro CMS
    label: "Hlavní Stránky" # Zobrazovaný název v administračním rozhraní
    files:
      - name: "index"
        file: "index.md"
        label: "Úvodní Stránka"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
          - {label: "Nadpis stránky (Title)", name: "title", widget: "string"}
          - {label: "Podnadpis (Subtitle)", name: "subtitle", widget: "string"}
          - {label: "Tělo obsahu (Markdown)", name: "body", widget: "markdown"}
      - name: "kontakty"
        file: "kontakty.md"
        label: "Stránka Kontakty"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
          - {label: "Nadpis", name: "title", widget: "string"}
          - {label: "Podnadpis", name: "subtitle", widget: "string"}
          - {label: "Tělo obsahu", name: "body", widget: "markdown"}
      - name: "rozvrh"
        file: "rozvrh.md"
        label: "Stránka Rozvrh akcí"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
          - {label: "Nadpis", name: "title", widget: "string"}
          - {label: "Podnadpis", name: "subtitle", widget: "string"}
          - {label: "Tělo obsahu", name: "body", widget: "markdown"}